# First notebook
## Importing documents and first cleaning.

### Information to consider according to the client:
- Classification model (Different targets), to predict best seller, supplier, product, line product, features, etc. 
- Regression model: Value per period of time
- Cost, profit and profit margin 
- Profit relation (supplier, seller, product, line, group, etc.)
- Inventory Turnover

## This notebook uses the following libraries: 
- pandas as pd: pandas is a library for data manipulation and analysis. It is imported and given the alias pd.
- glob: glob is a library for finding files and directories matching a specific pattern. It is used for searching for files.
- os: os is a library for interacting with the operating system. It is used for interacting with the file system.
- numpy as np: numpy is a library for numerical computing. It is imported and given the alias np.
- tqdm(tqdm.notebook): A progress bar for Jupyter notebooks

In [1]:
# import libraries
import pandas as pd
import numpy as np
import glob
import os
from tqdm.notebook import tqdm

#### The clientÂ´s documents where retrieved from a local ERP with limitation, therefore, I will import all the files and analyze what can be done from the clients requierements

In [2]:
%%time
# import sales documents from 2021 and concatenate them in 1 single database (& check time)
all_files = glob.glob(os.path.join(r"C:\Users\mfduh\OneDrive\Documents\Deutschland\Arbeiten\Data Analyst\Jupyter excercises\Week 9 - Final Project\Company_Documents\Projekt", "*.xls"))
ventas2021 = pd.concat((pd.read_excel(f) for f in tqdm(all_files, desc="Reading files")), ignore_index=True)

Reading files:   0%|          | 0/27 [00:00<?, ?it/s]

WARNING *** file size (46151374) not 512 + multiple of sector size (512)
WARNING *** file size (51881485) not 512 + multiple of sector size (512)
WARNING *** file size (24470440) not 512 + multiple of sector size (512)
WARNING *** file size (26049037) not 512 + multiple of sector size (512)
WARNING *** file size (47989418) not 512 + multiple of sector size (512)
WARNING *** file size (44010893) not 512 + multiple of sector size (512)
WARNING *** file size (62366586) not 512 + multiple of sector size (512)
WARNING *** file size (62216122) not 512 + multiple of sector size (512)
WARNING *** file size (40422564) not 512 + multiple of sector size (512)
WARNING *** file size (22254656) not 512 + multiple of sector size (512)
WARNING *** file size (28344120) not 512 + multiple of sector size (512)
WARNING *** file size (32657332) not 512 + multiple of sector size (512)
WARNING *** file size (64472985) not 512 + multiple of sector size (512)
WARNING *** file size (56123040) not 512 + multiple of sector size (512)
WARNING *** file size (55031695) not 512 + multiple of sector size (512)
WARNING *** file size (52040160) not 512 + multiple of sector size (512)
WARNING *** file size (50563248) not 512 + multiple of sector size (512)
WARNING *** file size (95069378) not 512 + multiple of sector size (512)
WARNING *** file size (53716402) not 512 + multiple of sector size (512)
WARNING *** file size (53952997) not 512 + multiple of sector size (512)
WARNING *** file size (29300029) not 512 + multiple of sector size (512)
WARNING *** file size (26245468) not 512 + multiple of sector size (512)
WARNING *** file size (47525124) not 512 + multiple of sector size (512)
WARNING *** file size (53360074) not 512 + multiple of sector size (512)
WARNING *** file size (49509077) not 512 + multiple of sector size (512)
WARNING *** file size (46388502) not 512 + multiple of sector size (512)
CPU times: total: 3min 15s
Wall time: 3min 26s

In [3]:
%%time
# import sales documents from 2022 and concatenate them in 1 single database (& check time)
all_files = glob.glob(os.path.join(r"C:\Users\mfduh\OneDrive\Documents\Deutschland\Arbeiten\Data Analyst\Jupyter excercises\Week 9 - Final Project\Company_Documents\2022 - Mensual", "*.xls"))
ventas2022 = pd.concat((pd.read_excel(f) for f in tqdm(all_files, desc="Reading files")), ignore_index=True)

Reading files:   0%|          | 0/18 [00:00<?, ?it/s]

WARNING *** file size (56401890) not 512 + multiple of sector size (512)
WARNING *** file size (56808414) not 512 + multiple of sector size (512)
WARNING *** file size (55197700) not 512 + multiple of sector size (512)
WARNING *** file size (60038112) not 512 + multiple of sector size (512)
WARNING *** file size (62184376) not 512 + multiple of sector size (512)
WARNING *** file size (80592714) not 512 + multiple of sector size (512)
WARNING *** file size (65508649) not 512 + multiple of sector size (512)
WARNING *** file size (62510451) not 512 + multiple of sector size (512)
WARNING *** file size (61960109) not 512 + multiple of sector size (512)
WARNING *** file size (59354768) not 512 + multiple of sector size (512)
WARNING *** file size (50903932) not 512 + multiple of sector size (512)
WARNING *** file size (54337539) not 512 + multiple of sector size (512)
WARNING *** file size (62197647) not 512 + multiple of sector size (512)
WARNING *** file size (64332657) not 512 + multiple of sector size (512)
WARNING *** file size (57905127) not 512 + multiple of sector size (512)
WARNING *** file size (52585328) not 512 + multiple of sector size (512)
WARNING *** file size (53012014) not 512 + multiple of sector size (512)
WARNING *** file size (51505757) not 512 + multiple of sector size (512)
CPU times: total: 2min 55s
Wall time: 3min

In [4]:
%%time
# import documents of the warehouse from 2021 and concatenate them in 1 single database (& check time)
all_files = glob.glob(os.path.join(r"C:\Users\mfduh\OneDrive\Documents\Deutschland\Arbeiten\Data Analyst\Jupyter excercises\Week 9 - Final Project\Company_Documents\2021 Existencias", "*.xls"))
exist2021 = pd.concat((pd.read_excel(f) for f in tqdm(all_files, desc="Reading files")), ignore_index=True)

Reading files:   0%|          | 0/12 [00:00<?, ?it/s]

WARNING *** file size (14922637) not 512 + multiple of sector size (512)
WARNING *** file size (14922274) not 512 + multiple of sector size (512)
WARNING *** file size (15787846) not 512 + multiple of sector size (512)
WARNING *** file size (14694658) not 512 + multiple of sector size (512)
WARNING *** file size (14642450) not 512 + multiple of sector size (512)
WARNING *** file size (15055362) not 512 + multiple of sector size (512)
WARNING *** file size (14934092) not 512 + multiple of sector size (512)
WARNING *** file size (14899979) not 512 + multiple of sector size (512)
WARNING *** file size (14980648) not 512 + multiple of sector size (512)
WARNING *** file size (15328355) not 512 + multiple of sector size (512)
WARNING *** file size (14952554) not 512 + multiple of sector size (512)
WARNING *** file size (14914323) not 512 + multiple of sector size (512)
CPU times: total: 23.8 s
Wall time: 26.8 s

In [5]:
%%time
# import documents of the warehouse from 2022 and concatenate them in 1 single database (& check time)
all_files = glob.glob(os.path.join(r"C:\Users\mfduh\OneDrive\Documents\Deutschland\Arbeiten\Data Analyst\Jupyter excercises\Week 9 - Final Project\Company_Documents\2022 Existencias", "*.xls"))
exist2022 = pd.concat((pd.read_excel(f) for f in tqdm(all_files, desc="Reading files")), ignore_index=True)

Reading files:   0%|          | 0/10 [00:00<?, ?it/s]

WARNING *** file size (14639158) not 512 + multiple of sector size (512)
WARNING *** file size (14393471) not 512 + multiple of sector size (512)
WARNING *** file size (14420431) not 512 + multiple of sector size (512)
WARNING *** file size (14491448) not 512 + multiple of sector size (512)
WARNING *** file size (14597972) not 512 + multiple of sector size (512)
WARNING *** file size (14608656) not 512 + multiple of sector size (512)
WARNING *** file size (14637303) not 512 + multiple of sector size (512)
WARNING *** file size (14653071) not 512 + multiple of sector size (512)
WARNING *** file size (13912804) not 512 + multiple of sector size (512)
WARNING *** file size (14186969) not 512 + multiple of sector size (512)
CPU times: total: 18.5 s
Wall time: 22.4 s

In [6]:
# allow the option to view all the columns of the document
pd.set_option('display.max_columns', None)

In [25]:
# concatenate the sales documents to have them as 1
ventas = pd.concat([ventas2021, ventas2022], axis=0)

In [26]:
# reseting index
ventas = ventas.reset_index(drop=True)

In [27]:
# check the database
ventas.head(3)

,FI,FF,TIPO,CLASE,ALMACEN,NALMACEN,CLASIFICACION,FECHA,EJERCICIO,MES,DIA,HORA,FOLIO,FACTURA,FECHA_FACTURA,FACTURA_CORTE,TIPOF,TIPO_PAGO,CLIENTE,NOMBRE,ZONA,TIPO_CLIENTE,VENDEDOR,NVENDEDOR,SECCION,TALLA,MODELO,COLOR,PRODUCTO,DESCRIPCION,GIRO,GRUPO,NGRUPO,SUBGRUPO,NSUBGRUPO,LINEA,MARCA,LISTAPRECIOS,LISTA,CANTIDAD,DESCUENTO,SUBTOTAL,IEPS,IVA,TOTAL,COSTO,UTILIDAD,MARGEN,UNIDAD,RANGO_MARGEN,PROV1,NPROV1,TASA_IEPS,TASA_IVA,USR1,USR2,USR3,USR4,USR5,PVCORTE,FECHA_PVCORTE,PVA,EXPORTACION,PEDIMENTO,PEDIMENTO_FECHA,PEDIMENTO_AGENTE,PEDIMENTO_NAGENTE,PEDIMENTO_IMPORTE,PEDIMENTO_TCAMBIO,INFORMAR,DESCUENTOS_POLITICA,DESCUENTOS_MANUALES,DESCUENTOS_GRUPO,DESCUENTOS_PAGO,DESCTO_EN_LISTA_CLIENTE,CLAVERANGO,CAJA,REMISION,Unnamed: 0,VENTA_NETA,Unnamed: 2,EXISTENCIA_ACTUAL,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66
0,2021-04-01 00:00:00,2021-04-15,PV,VENTA,T012,VILLASUNCION,NaN,2021-04-14,2021.0,4.0,14.0,13.0,T012009700,NaN,NaT,F012000414,CE,EF,00000,PUBLICO EN GENERAL,0.0,0.0,406.0,MA. ELENA MENDOZA DELGADO,UNISEX,T- CHICA,TELA,SURTIDO,3.0,ALMOHADA SIN MARCA BEBE SURTIDO UNISEX T- CHIC...,0.0,2.0,ALMOHADA,0.0,LINEA,BEBE,0.0,1.0,AGUASCALIENTES,1.0,0.0,25.86,0.0,4.14,30.0,NaN,NaN,NaN,H87,NaN,0008,ENRIQUE MEJIA TREJO,0.0,16.0,ESTAMPADA C/OLAN S/BOLSA,NaN,NaN,NaN,01ALMOOLBBCH,T012000402,2021-04-14,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,1.0,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-04-01 00:00:00,2021-04-15,PV,VENTA,T013,ALLENDE,NaN,2021-04-10,2021.0,4.0,10.0,17.0,T013017268,NaN,NaT,F013000455,CE,EF,00000,PUBLICO EN GENERAL,0.0,0.0,463.0,JUANA GUADALUPE GUTIERREZ MATINEZ,UNISEX,T- CHICA,TELA,SURTIDO,3.0,ALMOHADA SIN MARCA BEBE SURTIDO UNISEX T- CHIC...,0.0,2.0,ALMOHADA,0.0,LINEA,BEBE,0.0,1.0,AGUASCALIENTES,1.0,0.0,25.86,0.0,4.14,30.0,NaN,NaN,NaN,H87,NaN,0008,ENRIQUE MEJIA TREJO,0.0,16.0,ESTAMPADA C/OLAN S/BOLSA,NaN,NaN,NaN,01ALMOOLBBCH,T013000407,2021-04-10,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,1.0,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021-04-01 00:00:00,2021-04-15,PV,VENTA,T003,5 DE MAYO,NaN,2021-04-03,2021.0,4.0,3.0,15.0,T003036375,NaN,NaT,F003000630,CE,EF,00000,PUBLICO EN GENERAL,0.0,0.0,461.0,EDITH SANCHEZ,UNISEX,T- UNITALLA,VELOUR,SURTIDO,5.0,ALMOHADA T- UNITALLA LINEA SURTIDO BEBE ESTA...,0.0,2.0,ALMOHADA,0.0,LINEA,BEBE,26.0,1.0,AGUASCALIENTES,1.0,0.0,41.38,0.0,6.62,48.0,NaN,NaN,NaN,H87,NaN,0129,BABY REY,0.0,16.0,ESTAMPADA C/BOLSA,NaN,NaN,NaN,01ALRY2014BB,T003000422,2021-04-03,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,1.0,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
# check NaN values and display max_rows to view them correctly
pd.set_option('display.max_rows', None)
# ventas.isna().sum()

FI                            4193
FF                            4237
TIPO                          4237
CLASE                         4237
ALMACEN                       3980
NALMACEN                      4237
CLASIFICACION              1549333
FECHA                         4237
EJERCICIO                     4237
MES                           4237
DIA                           4237
HORA                          4237
FOLIO                         4237
FACTURA                    1545547
FECHA_FACTURA              1545547
FACTURA_CORTE                18876
TIPOF                         7902
TIPO_PAGO                     4237
CLIENTE                       4237
NOMBRE                        4310
ZONA                          4237
TIPO_CLIENTE                  4237
VENDEDOR                      4237
NVENDEDOR                     4237
SECCION                       4237
TALLA                        44785
MODELO                       25763
COLOR                        42109
PRODUCTO                      4237
DESCRIPCION                   4237
GIRO                          4237
GRUPO                         4237
NGRUPO                        4237
SUBGRUPO                      4237
NSUBGRUPO                    68382
LINEA                         4237
MARCA                         4237
LISTAPRECIOS                  4256
LISTA                         4300
CANTIDAD                      4193
DESCUENTO                     6664
SUBTOTAL                      4193
IEPS                          4193
IVA                           4193
TOTAL                         4193
COSTO                       887790
UTILIDAD                    887790
MARGEN                      887790
UNIDAD                        4237
RANGO_MARGEN                597033
PROV1                       105879
NPROV1                      106375
TASA_IEPS                     4193
TASA_IVA                      4193
USR1                        256047
USR2                       1518809
USR3                       1549333
USR4                       1549333
USR5                        840869
PVCORTE                       5440
FECHA_PVCORTE                 5440
PVA                          14299
EXPORTACION                   4237
PEDIMENTO                  1549333
PEDIMENTO_FECHA            1549333
PEDIMENTO_AGENTE           1549333
PEDIMENTO_NAGENTE          1549333
PEDIMENTO_IMPORTE          1549289
PEDIMENTO_TCAMBIO          1549289
INFORMAR                   1549333
DESCUENTOS_POLITICA        1442541
DESCUENTOS_MANUALES        1475098
DESCUENTOS_GRUPO           1345735
DESCUENTOS_PAGO            1549305
DESCTO_EN_LISTA_CLIENTE       4193
CLAVERANGO                  597033
CAJA                          4237
REMISION                      4237
Unnamed: 0                 1549310
VENTA_NETA                 1549332
Unnamed: 2                 1549333
EXISTENCIA_ACTUAL          1549333
Unnamed: 4                 1549333
Unnamed: 5                 1545172
Unnamed: 6                 1549333
Unnamed: 7                 1545170
Unnamed: 8                 1549333
Unnamed: 9                 1549333
Unnamed: 10                1545170
Unnamed: 11                1549333
Unnamed: 12                1545170
Unnamed: 13                1549333
Unnamed: 15                1549333
Unnamed: 16                1549077
Unnamed: 17                1547427
Unnamed: 18                1547428
Unnamed: 19                1548348
Unnamed: 20                1548349
Unnamed: 21                1548345
Unnamed: 22                1548346
Unnamed: 23                1547152
Unnamed: 24                1547153
Unnamed: 25                1549176
Unnamed: 26                1549177
Unnamed: 27                1548325
Unnamed: 28                1548326
Unnamed: 29                1548282
Unnamed: 30                1548283
Unnamed: 31                1547161
Unnamed: 32                1547162
Unnamed: 33                1548160
Unnamed: 34                1548161
Unnamed: 35                1548933
Unnamed: 36                1548934
Unnamed: 37                1548973
Unnamed: 38                1548974
Unnamed: 39                1548073
Unnamed: 40                1548074
Unnamed: 41                1548126
Unnamed: 42                1548127
Unnamed: 43                1548265
Unnamed: 44                1548266
Unnamed: 45                1548315
Unnamed: 46                1548316
Unnamed: 47                1548195
Unnamed: 48                1548196
Unnamed: 49                1548246
Unnamed: 50                1548247
Unnamed: 51                1548367
Unnamed: 52                1548368
Unnamed: 53                1548397
Unnamed: 54                1548398
Unnamed: 55                1547626
Unnamed: 56                1547627
Unnamed: 57                1548565
Unnamed: 58                1548566
Unnamed: 59                1548805
Unnamed: 60                1548806
Unnamed: 61                1548344
Unnamed: 62                1548345
Unnamed: 63                1548517
Unnamed: 64                1548518
Unnamed: 65                1545143
Unnamed: 66                1545144
dtype: int64

In [29]:
# check specific columns
ventas['RANGO_MARGEN'].isna().sum()

597033

In [30]:
# There are many columns with no or very little information, after checking them, I decided to drop columns with a thresh of 600,000
ventas = ventas.dropna(axis = 1, thresh = 600000)

In [31]:
# check NaN values again
ventas.isna().sum()

FI                           4193
FF                           4237
TIPO                         4237
CLASE                        4237
ALMACEN                      3980
NALMACEN                     4237
FECHA                        4237
EJERCICIO                    4237
MES                          4237
DIA                          4237
HORA                         4237
FOLIO                        4237
FACTURA_CORTE               18876
TIPOF                        7902
TIPO_PAGO                    4237
CLIENTE                      4237
NOMBRE                       4310
ZONA                         4237
TIPO_CLIENTE                 4237
VENDEDOR                     4237
NVENDEDOR                    4237
SECCION                      4237
TALLA                       44785
MODELO                      25763
COLOR                       42109
PRODUCTO                     4237
DESCRIPCION                  4237
GIRO                         4237
GRUPO                        4237
NGRUPO                       4237
SUBGRUPO                     4237
NSUBGRUPO                   68382
LINEA                        4237
MARCA                        4237
LISTAPRECIOS                 4256
LISTA                        4300
CANTIDAD                     4193
DESCUENTO                    6664
SUBTOTAL                     4193
IEPS                         4193
IVA                          4193
TOTAL                        4193
COSTO                      887790
UTILIDAD                   887790
MARGEN                     887790
UNIDAD                       4237
RANGO_MARGEN               597033
PROV1                      105879
NPROV1                     106375
TASA_IEPS                    4193
TASA_IVA                     4193
USR1                       256047
USR5                       840869
PVCORTE                      5440
FECHA_PVCORTE                5440
PVA                         14299
EXPORTACION                  4237
DESCTO_EN_LISTA_CLIENTE      4193
CLAVERANGO                 597033
CAJA                         4237
REMISION                     4237
dtype: int64

In [34]:
# checked the different columns, values and relevance for the Analysis 
# and return max_rows to 10
pd.set_option('display.max_rows', 10)
ventas['VENDEDOR'].value_counts(dropna = False)

66.0     66962
112.0    54453
116.0    53516
131.0    50329
495.0    46626
         ...
97.0         1
111.0        1
384.0        1
421.0        1
193.0        1
Name: VENDEDOR, Length: 334, dtype: int64

In [35]:
ventas.head(3)

,FI,FF,TIPO,CLASE,ALMACEN,NALMACEN,FECHA,EJERCICIO,MES,DIA,HORA,FOLIO,FACTURA_CORTE,TIPOF,TIPO_PAGO,CLIENTE,NOMBRE,ZONA,TIPO_CLIENTE,VENDEDOR,NVENDEDOR,SECCION,TALLA,MODELO,COLOR,PRODUCTO,DESCRIPCION,GIRO,GRUPO,NGRUPO,SUBGRUPO,NSUBGRUPO,LINEA,MARCA,LISTAPRECIOS,LISTA,CANTIDAD,DESCUENTO,SUBTOTAL,IEPS,IVA,TOTAL,COSTO,UTILIDAD,MARGEN,UNIDAD,RANGO_MARGEN,PROV1,NPROV1,TASA_IEPS,TASA_IVA,USR1,USR5,PVCORTE,FECHA_PVCORTE,PVA,EXPORTACION,DESCTO_EN_LISTA_CLIENTE,CLAVERANGO,CAJA,REMISION
0,2021-04-01 00:00:00,2021-04-15,PV,VENTA,T012,VILLASUNCION,2021-04-14,2021.0,4.0,14.0,13.0,T012009700,F012000414,CE,EF,00000,PUBLICO EN GENERAL,0.0,0.0,406.0,MA. ELENA MENDOZA DELGADO,UNISEX,T- CHICA,TELA,SURTIDO,3.0,ALMOHADA SIN MARCA BEBE SURTIDO UNISEX T- CHIC...,0.0,2.0,ALMOHADA,0.0,LINEA,BEBE,0.0,1.0,AGUASCALIENTES,1.0,0.0,25.86,0.0,4.14,30.0,NaN,NaN,NaN,H87,NaN,0008,ENRIQUE MEJIA TREJO,0.0,16.0,ESTAMPADA C/OLAN S/BOLSA,01ALMOOLBBCH,T012000402,2021-04-14,N,N,0.0,NaN,1.0,N
1,2021-04-01 00:00:00,2021-04-15,PV,VENTA,T013,ALLENDE,2021-04-10,2021.0,4.0,10.0,17.0,T013017268,F013000455,CE,EF,00000,PUBLICO EN GENERAL,0.0,0.0,463.0,JUANA GUADALUPE GUTIERREZ MATINEZ,UNISEX,T- CHICA,TELA,SURTIDO,3.0,ALMOHADA SIN MARCA BEBE SURTIDO UNISEX T- CHIC...,0.0,2.0,ALMOHADA,0.0,LINEA,BEBE,0.0,1.0,AGUASCALIENTES,1.0,0.0,25.86,0.0,4.14,30.0,NaN,NaN,NaN,H87,NaN,0008,ENRIQUE MEJIA TREJO,0.0,16.0,ESTAMPADA C/OLAN S/BOLSA,01ALMOOLBBCH,T013000407,2021-04-10,N,N,0.0,NaN,1.0,N
2,2021-04-01 00:00:00,2021-04-15,PV,VENTA,T003,5 DE MAYO,2021-04-03,2021.0,4.0,3.0,15.0,T003036375,F003000630,CE,EF,00000,PUBLICO EN GENERAL,0.0,0.0,461.0,EDITH SANCHEZ,UNISEX,T- UNITALLA,VELOUR,SURTIDO,5.0,ALMOHADA T- UNITALLA LINEA SURTIDO BEBE ESTA...,0.0,2.0,ALMOHADA,0.0,LINEA,BEBE,26.0,1.0,AGUASCALIENTES,1.0,0.0,41.38,0.0,6.62,48.0,NaN,NaN,NaN,H87,NaN,0129,BABY REY,0.0,16.0,ESTAMPADA C/BOLSA,01ALRY2014BB,T003000422,2021-04-03,N,N,0.0,NaN,1.0,N

In [36]:
# After speaking to the client: drop unnecesary columns
# A couple are pending to check the utility, meanwhile theyÂ´ll be kept
ventas = ventas.drop(columns=['FI', 'FF', 'TIPO', 'NALMACEN','FECHA', 'FOLIO', 'FACTURA_CORTE', 
                            'TIPOF', 'CLIENTE', 'NOMBRE', 'ZONA', 'TIPO_CLIENTE', 'NVENDEDOR', 
                              'GIRO', 'GRUPO', 'SUBGRUPO', 'LISTAPRECIOS', 'IEPS', 'UTILIDAD',
                              'MARGEN', 'UNIDAD', 'RANGO_MARGEN', 'NPROV1', 'TASA_IEPS',
                              'TASA_IVA','USR5', 'PVCORTE', 'FECHA_PVCORTE', 'PVA', 'EXPORTACION',
                              'DESCTO_EN_LISTA_CLIENTE', 'CLAVERANGO', 'CAJA', 'REMISION'], axis=1)

In [37]:
ventas.shape

(1549333, 27)

In [38]:
# standarize columns
def column_change(df):
    cols = []
    for column in range(len(df.columns)):
        cols.append(df.columns[column].lower().replace(' ', '_'))
    df.columns = cols
    return

column_change(ventas)

In [40]:
ventas

,clase,almacen,ejercicio,mes,dia,hora,tipo_pago,vendedor,seccion,talla,modelo,color,producto,descripcion,ngrupo,nsubgrupo,linea,marca,lista,cantidad,descuento,subtotal,iva,total,costo,prov1,usr1
0,VENTA,T012,2021.0,4.0,14.0,13.0,EF,406.0,UNISEX,T- CHICA,TELA,SURTIDO,3.0,ALMOHADA SIN MARCA BEBE SURTIDO UNISEX T- CHIC...,ALMOHADA,LINEA,BEBE,0.0,AGUASCALIENTES,1.0,0.00,25.86,4.14,30.00,NaN,0008,ESTAMPADA C/OLAN S/BOLSA
1,VENTA,T013,2021.0,4.0,10.0,17.0,EF,463.0,UNISEX,T- CHICA,TELA,SURTIDO,3.0,ALMOHADA SIN MARCA BEBE SURTIDO UNISEX T- CHIC...,ALMOHADA,LINEA,BEBE,0.0,AGUASCALIENTES,1.0,0.00,25.86,4.14,30.00,NaN,0008,ESTAMPADA C/OLAN S/BOLSA
2,VENTA,T003,2021.0,4.0,3.0,15.0,EF,461.0,UNISEX,T- UNITALLA,VELOUR,SURTIDO,5.0,ALMOHADA T- UNITALLA LINEA SURTIDO BEBE ESTA...,ALMOHADA,LINEA,BEBE,26.0,AGUASCALIENTES,1.0,0.00,41.38,6.62,48.00,NaN,0129,ESTAMPADA C/BOLSA
3,VENTA,T003,2021.0,4.0,4.0,17.0,EF,458.0,UNISEX,T- UNITALLA,VELOUR,SURTIDO,5.0,ALMOHADA T- UNITALLA LINEA SURTIDO BEBE ESTA...,ALMOHADA,LINEA,BEBE,26.0,DISTRIBUIDOR,1.0,0.00,36.21,5.79,42.00,NaN,0129,ESTAMPADA C/BOLSA
4,VENTA,T003,2021.0,4.0,10.0,16.0,EF,461.0,UNISEX,T- UNITALLA,VELOUR,SURTIDO,5.0,ALMOHADA T- UNITALLA LINEA SURTIDO BEBE ESTA...,ALMOHADA,LINEA,BEBE,26.0,AGUASCALIENTES,1.0,0.00,41.38,6.62,48.00,NaN,0129,ESTAMPADA C/BOLSA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1549328,VENTA,T018,2022.0,9.0,29.0,13.0,EF,131.0,INVIERNO,T- UNITALLA,FLANEL,SURTIDO,4302.0,PIJAMA T- UNITALLA SURTIDO DAMA DM01 FLANE...,PIJAMA,NaN,DAMA,0317,AGUASCALIENTES,1.0,0.00,103.45,16.55,120.00,5.862170e+01,0037,DM01
1549329,VENTA,T019,2022.0,9.0,20.0,16.0,EF,608.0,INVIERNO,T- UNITALLA,FLANEL,SURTIDO,4302.0,PIJAMA T- UNITALLA SURTIDO DAMA DM01 FLANE...,PIJAMA,NaN,DAMA,0317,AGUASCALIENTES,1.0,0.00,103.45,16.55,120.00,5.862170e+01,0037,DM01
1549330,VENTA,T019,2022.0,9.0,23.0,13.0,EF,608.0,INVIERNO,T- UNITALLA,FLANEL,SURTIDO,4302.0,PIJAMA T- UNITALLA SURTIDO DAMA DM01 FLANE...,PIJAMA,NaN,DAMA,0317,AGUASCALIENTES,1.0,0.00,103.45,16.55,120.00,5.862170e+01,0037,DM01
1549331,VENTA,T022,2022.0,9.0,17.0,12.0,EF,606.0,INVIERNO,T- UNITALLA,FLANEL,SURTIDO,4302.0,PIJAMA T- UNITALLA SURTIDO DAMA DM01 FLANE...,PIJAMA,NaN,DAMA,0317,AGUASCALIENTES,1.0,0.00,103.45,16.55,120.00,5.862170e+01,0037,DM01
1549332,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52891.0,103782.99,2245808.56,359332.71,2605141.27,1.470139e+06,NaN,NaN

In [41]:
# drop last row as it is only NaN values
ventas = ventas.drop(index=1549332)

In [43]:
# check NaN values and display max_rows to view them correctly
pd.set_option('display.max_rows', None)
ventas.isna().sum()

clase            4236
almacen          3979
ejercicio        4236
mes              4236
dia              4236
hora             4236
tipo_pago        4236
vendedor         4236
seccion          4236
talla           44784
modelo          25762
color           42108
producto         4236
descripcion      4236
ngrupo           4236
nsubgrupo       68381
linea            4236
marca            4236
lista            4299
cantidad         4193
descuento        6664
subtotal         4193
iva              4193
total            4193
costo          887790
prov1          105878
usr1           256046
dtype: int64

In [ ]:
# save the first draft of the document that will be used to analyse as a CSV.
ventas.to_csv('ventas_completo.csv', index=False)

### Check documents of the warehouse

In [44]:
# concatenate both years
existencias = pd.concat([exist2021, exist2022], axis=0)

In [ ]:
# reset indexes
existencias = existencias.reset_index(drop=True)

In [45]:
# display max_rows to 10 and check the document
pd.set_option('display.max_rows', 10)
existencias

,ALMACEN,NALMACEN,PRODUCTO,DESCRIPCION,GIRO,SECCION,GRUPO,SUBGRUPO,LINEA,PROV1,NPROV1,COSTO_BASE,PRECIO_1,PRECIO_2,DIAS_ULTIMA_VENTA,VENTA_NETA,EXISTENCIA_ACTUAL,COSTO_UNITARIO,ARTISTA,TITULO
0,APA,APARTADOS,212.0,BRASIER T- UNITALLA LINEA SURTIDO DAMA DOBLE...,0.0,INTERIOR,BRASIER,LINEA,5.0,0002,ALBERTO PEREZ ESCOTO,5.603448e+01,9.482759e+01,9.051724e+01,NaN,0,5,5.747780e+01,DOBLE PUSH COPA B,NaN
1,APA,APARTADOS,229.0,CONJUNTO PANTS T- 1/3 LINEA SURTIDO NIÃO C/C...,0.0,INVIERNO,CONJUNTO PANTS,LINEA,3.0,0008,ENRIQUE MEJIA TREJO,1.150000e+02,1.724138e+02,1.681035e+02,NaN,0,2,9.694720e+01,C/CHALECO,NaN
2,APA,APARTADOS,230.0,CONJUNTO PANTS TRAPINES NIÃA SURTIDO FEMENINO ...,0.0,FEMENINO,CONJUNTO PANTS,LINEA,2.0,0008,ENRIQUE MEJIA TREJO,9.482759e+01,1.637931e+02,1.594828e+02,NaN,0,2,9.586330e+01,CHALECO,NaN
3,APA,APARTADOS,239.0,CALCETA MARCEL BEBE SURTIDO UNISEX T- 1/3 LIKR...,0.0,UNISEX,CALCETA,PROMOCION,1.0,0008,ENRIQUE MEJIA TREJO,2.508620e+00,5.172410e+00,4.310340e+00,NaN,0,12,3.062700e+00,LISA,NaN
4,APA,APARTADOS,240.0,CALCETA MARCEL BEBE SURTIDO UNISEX T- 3/5 LIKR...,0.0,UNISEX,CALCETA,PROMOCION,1.0,0008,ENRIQUE MEJIA TREJO,2.873560e+00,5.172410e+00,4.310340e+00,NaN,0,12,3.221800e+00,LISA,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279939,TRA,TRANSITO,4342.0,CONJUNTO SUDADERA CH-G SURTIDO NIÃA ESTAMPA...,0.0,INVIERNO,CONJUNTO SUDADERA,NaN,2.0,0189,TEXTICUITZEO,1.500000e+02,2.241379e+02,2.198276e+02,NaN,0,6,1.293103e+02,ESTAMPADO BORDADO,NaN
279940,TRA,TRANSITO,4352.0,PIJAMA T- UNITALLA PIJAMA SURTIDO DAMA JOGGE...,0.0,INVIERNO,PIJAMA,PIJAMA,5.0,0037,XIN FENG SHAN,8.300000e+01,1.250000e+02,1.206897e+02,NaN,0,7,7.155170e+01,JOGGER 4849-3,NaN
279941,TRA,TRANSITO,4353.0,SUDADERA T- UNITALLA LINEA SURTIDO DAMA 4849...,0.0,INVIERNO,SUDADERA,LINEA,5.0,0037,XIN FENG SHAN,9.400000e+01,1.422414e+02,1.379310e+02,NaN,0,5,8.103450e+01,4849-2,NaN
279942,TRA,TRANSITO,4354.0,PANTALON T- UNITALLA LINEA SURTIDO DAMA MK30...,0.0,FEMENINO,PANTALON,LINEA,5.0,0037,XIN FENG SHAN,7.200000e+01,1.077586e+02,1.034483e+02,NaN,0,40,6.206890e+01,MK3002C,NaN
279943,27486,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.369672e+06,2.138343e+06,2.114201e+06,2146755.0,109878,554129,1.217496e+06,NaN,NaN

In [47]:
# drop last row as it is only NaN values
existencias = existencias.drop(index=279943)

In [49]:
existencias.head(2)

,ALMACEN,NALMACEN,PRODUCTO,DESCRIPCION,GIRO,SECCION,GRUPO,SUBGRUPO,LINEA,PROV1,NPROV1,COSTO_BASE,PRECIO_1,PRECIO_2,DIAS_ULTIMA_VENTA,VENTA_NETA,EXISTENCIA_ACTUAL,COSTO_UNITARIO,ARTISTA,TITULO
0,APA,APARTADOS,212.0,BRASIER T- UNITALLA LINEA SURTIDO DAMA DOBLE...,0.0,INTERIOR,BRASIER,LINEA,5.0,0002,ALBERTO PEREZ ESCOTO,56.03448,94.82759,90.51724,NaN,0,5,57.4778,DOBLE PUSH COPA B,NaN
1,APA,APARTADOS,229.0,CONJUNTO PANTS T- 1/3 LINEA SURTIDO NIÃO C/C...,0.0,INVIERNO,CONJUNTO PANTS,LINEA,3.0,0008,ENRIQUE MEJIA TREJO,115.00000,172.41379,168.10345,NaN,0,2,96.9472,C/CHALECO,NaN

In [50]:
existencias.isna().sum()

ALMACEN                   0
NALMACEN                 21
PRODUCTO                 21
DESCRIPCION              21
GIRO                     21
                      ...
VENTA_NETA                0
EXISTENCIA_ACTUAL         0
COSTO_UNITARIO            0
ARTISTA               91497
TITULO               619369
Length: 20, dtype: int64

In [48]:
# save the first draft of the document that will be used to analyse as a CSV.
existencias.to_csv('existencias_completo.csv', index=False)